### ISSUE TITLE
Bug: Crash wenn Bot Fuchs fängt

### ISSUE THREAD

**Issue by eauw** [eauw/bomberman-server#24]

**Comment by eauw** [comment]
2016/06/15 19:17:41 waiting for commands
2016/06/15 19:17:43 Message >d< received from player >Player2<
2016/06/15 19:17:45 Message >n< received from player >Player1<
2016/06/15 19:17:45 Processing Round 13
panic: runtime error: index out of range

goroutine 22 [running]:
panic(0x3c1000, 0xc820010080)
    /usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:464 +0x3e6
github.com/eauw/bomberman-server/gamemanager.(_Manager).GameState(0xc82008c090, 0xc820416700, 0x335, 0x0, 0x0)
    /Users/eugen/go/src/github.com/eauw/bomberman-server/gamemanager/Gamemanager.go:215 +0x13df
github.com/eauw/bomberman-server/gamemanager.(_Manager).sendGameStateToPlayer(0xc82008c090, 0xc82013ae60)
    /Users/eugen/go/src/github.com/eauw/bomberman-server/gamemanager/Gamemanager.go:522 +0xd7
github.com/eauw/bomberman-server/gamemanager.(_Manager).broadcastGamestate(0xc82008c090)
    /Users/eugen/go/src/github.com/eauw/bomberman-server/gamemanager/Gamemanager.go:512 +0xa6
github.com/eauw/bomberman-server/gamemanager.(_Manager).ProcessRound(0xc82008c090, 0xc820075d90)
    /Users/eugen/go/src/github.com/eauw/bomberman-server/gamemanager/Gamemanager.go:449 +0xc0c
github.com/eauw/bomberman-server/gamemanager.(*Manager).channelHandler(0xc82008c090)
    /Users/eugen/go/src/github.com/eauw/bomberman-server/gamemanager/Gamemanager.go:246 +0x139
created by github.com/eauw/bomberman-server/gamemanager.NewManager
    /Users/eugen/go/src/github.com/eauw/bomberman-server/gamemanager/Gamemanager.go:42 +0x1b2
